### ISSUE TITLE
Test and fix issues to do with touch events. 

### ISSUE THREAD

**Issue by phtaylor** [ZeaInc/zea-ux#79]
simulate touch events. 
mess around with the aim solver live sample. 

try cloning the glitch demo, link to a local build of ux.

**Comment by apajaro** [comment]
There is an issue with iOS devices, I'm assigning this to @phtaylor because he understands better the problem. Check my [comment](https://github.com/ZeaInc/zea-ux/pull/85#issuecomment-710542327) in the PR
